#!/usr/bin/env sh
mkdir -p .cache
cd .cache
if [[ ! -f ktlint ]]
then
    curl -sSLO  https://github.com/pinterest/ktlint/releases/download/0.34.0/ktlint
    chmod 755 ktlint
fi
cd ..

changed_kotlin_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*kt$" )
echo ${changed_kotlin_files}
comma_files=$(echo "${changed_kotlin_files}" | paste -s -d "," -)
echo ${comma_files}
.cache/ktlint -F ${changed_kotlin_files}
git add $(echo "${changed_kotlin_files}" | paste -s -d " " -)
